server:
  port: 10003

spring:
  application:
    name: cloud-order

  datasource:
    druid:
      ######### 核心配置 #########
      url: jdbc:mysql://192.168.174.11:3306/explore_order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      ######### 可选配置 #########
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000

mybatis:
  type-aliases-package: com.explore.order.mapper
  mapper-locations: classpath:*.xml

logging:
  level:
    com.explore.order.mapper: debug