server:
  port: 10002

spring:
  application:
    name: cloud-product
  main:
    allow-circular-references: true
  datasource:
    druid:
      ######### 核心数据源配置 #########
      url: jdbc:mysql://192.168.174.11:3306/explore_product?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      ######### 可选配置 #########
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.174.11:8848
        username: nacos
        password: nacos
        namespace: 5f5b189f-1d18-4478-ad4e-e186e60310a8
        group: CLOUD_GROUP
    sentinel:
      transport:
        dashboard: 192.168.174.11:8080
        port: 8719
  zipkin:
    base-url: http://192.168.174.11:9411
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0

# Feign 启用Sentinel实现服务降级、熔断
feign:
  sentinel:
    enabled: true


mybatis:
  type-aliases-package: com.explore.product.mapper
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.explore.product.mapper: debug

seata:
  enabled: true
  tx-service-group: cloud_product_tx_group
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.174.11:8848
      namespace: 2b21d738-f843-46c5-9063-7c6413fb003a
      group: SEATA_GROUP
      application: seata-server
  config:
    type: nacos
    nacos:
      namespace: 2b21d738-f843-46c5-9063-7c6413fb003a
      group: SEATA_GROUP
      server-addr: 192.168.174.11:8848
